### PR TITLE
[styles] arranged styles for buttons to add and remove fields on the editor

### PR DESCRIPTION
**Pull request by gastonche**
Fixed the style of the control buttons on the basic editor. Clean up task

### CODE REVIEW

**Comment by nemesisdesign** [comment]
Fix the authorship of the commit (email mismatch) and then go ahead, ok?

**Comment by gastonche** [comment]
okay, will do that

**Comment by nemesisdesign** [comment]
@gastonche looking forward to it

**Comment by nemesisdesign** [comment]
@gastonche ping

**Pull request merged**
